package com.jhz.movielens.hadoop.quality;

public enum IssueCode {
    EMPTY_LINE,
    FIELD_COUNT_MISMATCH,
    REQUIRED_FIELD_MISSING,
    INVALID_INTEGER,
    INVALID_LONG,
    NON_POSITIVE_IDENTIFIER,
    RATING_OUT_OF_RANGE,
    NON_POSITIVE_TIMESTAMP,
    INVALID_GENDER,
    INVALID_AGE_CATEGORY,
    INVALID_OCCUPATION_CATEGORY,
    EMPTY_GENRE,
    DUPLICATE_GENRE,
    UNKNOWN_GENRE
}
